### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by TheNorthBear** [funkemunky/Iris-Issues#109]
**Describe the bug**
I used Killaura and the Console print some issues out.

**Version Information**
- Iris Anticheat Version ( 1.8.9 : Jun 18, 2019 ): 
- Atlas Version (1.3.1): 
- Bukkit/Spigot Version (1.8.8): 

**Are you using the ViaVersion plugin?**: 

**Server Logs (Pastebin link)**
[10:00:26] [Craft Scheduler Thread - 0/INFO]: Server channel handler injected ([id: 0x78b174e3, /0:0:0:0:0:0:0:0:25568])
[10:00:33] [Thread-9/INFO]: UUID of player TheNorthBear is f953dec3-43e9-3916-823d-861129c826f7
[10:00:33] [Server thread/INFO]: TheNorthBear[/127.0.0.1:49568] logged in with entity id 196 at ([world]85.32061459983048, 93.0, 10.863061516304116)
[10:00:36] [pool-8-thread-1/WARN]: Exception in thread "pool-8-thread-1" 
[10:00:36] [pool-8-thread-1/WARN]: java.util.ConcurrentModificationException
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.LinkedList$ListItr.next(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.lang.Iterable.forEach(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at dMYH.onPacket(SpeedB.java:72)
[10:00:36] [pool-8-thread-1/WARN]: 	at tIUB.lambda$null$0(PacketListeners.java:179)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at tIUB.lambda$hopper$1(PacketListeners.java:177)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[10:00:36] [pool-8-thread-1/WARN]: 	at java.lang.Thread.run(Unknown Source)
[10:01:48] [Server thread/INFO]: TheNorthBear lost connection: Disconnected
[10:01:48] [Server thread/INFO]: TheNorthBear left the game.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) I did this, with Killaura, and i have issues in my console
2) Another Bug: When i use Killaura the execCommands will be not used, and the value rise up. And I think the other Killaura detecter dosnt work
3) .....

**Screenshots/Video**
-----

**Additional context**
-----

**Comment by FozzieHi** [comment]
If the error is only once then it is probably not an issue. This is bound to happen at least once with multithreaded plugins.

the execCommands will only execute when you real the executableVL level per check in your config file.
