### ISSUE TITLE
More spam in the console with zspigot

### ISSUE THREAD

**Issue by hiimcapri** [funkemunky/Iris-Issues#34]
**Describe the bug**

**Version Information**
- Iris Anticheat Version 1.5.6
- Atlas Version 1.0.8
- Bukkit/Spigot Version zspigot 1.7.10

**Server Logs**
[04:28:27 WARN]: java.lang.reflect.InvocationTargetException
[04:28:27 WARN]:        at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[04:28:27 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[04:28:27 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[04:28:27 WARN]:        at cc.funkemunky.api.event.system.EventManager.call(EventManager.java:62)
[04:28:27 WARN]:        at cc.funkemunky.api.event.system.EventManager.lambda$callEvent$1(EventManager.java:45)
[04:28:27 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[04:28:27 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[04:28:27 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[04:28:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[04:28:27 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[04:28:27 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:28:27 WARN]: Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
[04:28:27 WARN]:        at cc.funkemunky.api.utils.BoundingBox.collides(BoundingBox.java:158)
[04:28:27 WARN]:        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[04:28:27 WARN]:        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[04:28:27 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[04:28:27 WARN]:        at cc.funkemunky.api.utils.blockbox.boxes.BlockBox1_7_R4.getCollidingBoxes(BlockBox1_7_R4.java:59)
[04:28:27 WARN]:        at Sjyh.update(MovementProcessor.java:45)
[04:28:27 WARN]:        at vPZG.onEvent(PacketListeners.java:130)
[04:28:27 WARN]:        ... 11 more

**How to re-create**
just console spam..

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

**Additional context**

**Comment by funkemunky** [comment]
Let me know if this is still an issue in the latest update.
