### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by quantumcomputers** [funkemunky/Iris-Issues#54]
**Describe the bug**

**Version Information**
- Iris Anticheat Version 1.6.4
- Atlas Version 1.1.1
- Bukkit/Spigot Version 1.7.10 zspigot, 1.7.10  paperspigot and 1.7.10   craftbukkit spigot ( all have the same issue)

**Server Logs**
Provide the server log of the time the bug occurred.

**How to re-create**
Describe in detail how we can re-create this bug.
Steps: 
1) install atlas and iris.
2)  run the server
3) log into the server it will spam console and iris and atlas will not work

**Screenshots/Video**
If applicable, add screenshots or videos to help explain your problem.

[iris issue video.zip](https://github.com/funkemunky/Iris-Issues/files/2852829/iris.issue.video.zip)

**Additional context**

console log 

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
This PaperSpigot build only supports Minecraft 1.7.x and 1.8.x clients!
*** It is imperative that backups be taken before running this build on your server! ***
Please report issues directly to Paper, and always ensure you're up-to-date!
*** Any bug reports not running the very latest version of the software will be ignored ***

[13:56:09 INFO]: Starting minecraft server version 1.7.10
[13:56:09 INFO]: Loading properties
[13:56:09 INFO]: Default game type: SURVIVAL
[13:56:09 INFO]: This server is running CraftBukkit version git-PaperSpigot-1f7d532 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[13:56:09 INFO]: Debug logging is disabled
[13:56:09 INFO]: Server Ping Player Sample Count: 12
[13:56:09 INFO]: Using 4 threads for Netty based IO
[13:56:09 INFO]: Generating keypair
[13:56:09 INFO]: Starting Minecraft server on *:25565
[13:56:10 INFO]: Set PluginClassLoader as parallel capable
[13:56:10 INFO]: [Atlas] Loading Atlas v1.1.1
[13:56:10 INFO]: [Iris] Loading Iris v1.6.4
[13:56:10 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[13:56:10 INFO]: Preparing level "world"
[13:56:10 INFO]: -------- World Settings For [world] --------
[13:56:10 INFO]: View Distance: 10
[13:56:10 INFO]: Chunks to Grow per Tick: 650
[13:56:10 INFO]: Clear tick list: false
[13:56:10 INFO]: Experience Merge Radius: 3.0
[13:56:10 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:10 INFO]: Max Entity Collisions: 8
[13:56:10 INFO]: Arrow Despawn Rate: 1200
[13:56:10 INFO]: Item Merge Radius: 2.5
[13:56:10 INFO]: Item Despawn Rate: 6000
[13:56:10 INFO]: Anti X-Ray: true
[13:56:10 INFO]:        Engine Mode: 1
[13:56:10 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:10 INFO]:        Replace Blocks: [1, 5]
[13:56:10 INFO]: Cactus Growth Modifier: 100%
[13:56:10 INFO]: Cane Growth Modifier: 100%
[13:56:10 INFO]: Melon Growth Modifier: 100%
[13:56:10 INFO]: Mushroom Growth Modifier: 100%
[13:56:10 INFO]: Pumpkin Growth Modifier: 100%
[13:56:10 INFO]: Sapling Growth Modifier: 100%
[13:56:10 INFO]: Wheat Growth Modifier: 100%
[13:56:10 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:10 INFO]: Mob Spawn Range: 4
[13:56:10 INFO]: Nerfing mobs spawned from spawners: false
[13:56:10 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:10 INFO]: Sending up to 5 chunks per packet
[13:56:10 INFO]: Max TNT Explosions: 100
[13:56:10 INFO]: Alternative Hopper Ticking: false
[13:56:10 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:10 INFO]: Structure Info Saving: true
[13:56:10 INFO]: Random Lighting Updates: false
[13:56:10 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:10 INFO]: Zombie Aggressive Towards Villager: true
[13:56:10 INFO]: -------- World Settings For [world] --------
[13:56:10 INFO]: Keep spawn chunk loaded: true
[13:56:10 INFO]: WorldServer TickNextTickList cap set at 10000
[13:56:10 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[13:56:10 INFO]: World async lighting: false
[13:56:10 INFO]: Remove invalid mob spawner tile entities: true
[13:56:10 INFO]: Player blocking damage multiplier set to 0.5
[13:56:10 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[13:56:10 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[13:56:10 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[13:56:10 INFO]: Water over lava flow speed: 5
[13:56:10 INFO]: Inverted Redstone Lamps: false
[13:56:10 INFO]: Allow undead horse types to be leashed: true
[13:56:10 INFO]: -------- World Settings For [world_nether] --------
[13:56:10 INFO]: View Distance: 10
[13:56:10 INFO]: Chunks to Grow per Tick: 650
[13:56:10 INFO]: Clear tick list: false
[13:56:10 INFO]: Experience Merge Radius: 3.0
[13:56:10 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:10 INFO]: Max Entity Collisions: 8
[13:56:10 INFO]: Arrow Despawn Rate: 1200
[13:56:10 INFO]: Item Merge Radius: 2.5
[13:56:10 INFO]: Item Despawn Rate: 6000
[13:56:10 INFO]: Anti X-Ray: true
[13:56:10 INFO]:        Engine Mode: 1
[13:56:10 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:10 INFO]:        Replace Blocks: [1, 5]
[13:56:10 INFO]: Cactus Growth Modifier: 100%
[13:56:10 INFO]: Cane Growth Modifier: 100%
[13:56:10 INFO]: Melon Growth Modifier: 100%
[13:56:10 INFO]: Mushroom Growth Modifier: 100%
[13:56:10 INFO]: Pumpkin Growth Modifier: 100%
[13:56:10 INFO]: Sapling Growth Modifier: 100%
[13:56:10 INFO]: Wheat Growth Modifier: 100%
[13:56:10 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:10 INFO]: Mob Spawn Range: 4
[13:56:10 INFO]: Nerfing mobs spawned from spawners: false
[13:56:10 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:10 INFO]: Sending up to 5 chunks per packet
[13:56:10 INFO]: Max TNT Explosions: 100
[13:56:10 INFO]: Alternative Hopper Ticking: false
[13:56:10 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:10 INFO]: Structure Info Saving: true
[13:56:10 INFO]: Random Lighting Updates: false
[13:56:10 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:10 INFO]: Zombie Aggressive Towards Villager: true
[13:56:10 INFO]: -------- World Settings For [world_nether] --------
[13:56:10 INFO]: Keep spawn chunk loaded: true
[13:56:10 INFO]: WorldServer TickNextTickList cap set at 10000
[13:56:10 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[13:56:10 INFO]: World async lighting: false
[13:56:10 INFO]: Remove invalid mob spawner tile entities: true
[13:56:10 INFO]: Player blocking damage multiplier set to 0.5
[13:56:10 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[13:56:10 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[13:56:10 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[13:56:10 INFO]: Water over lava flow speed: 5
[13:56:10 INFO]: Inverted Redstone Lamps: false
[13:56:10 INFO]: Allow undead horse types to be leashed: true
[13:56:10 INFO]: -------- World Settings For [world_the_end] --------
[13:56:10 INFO]: View Distance: 10
[13:56:10 INFO]: Chunks to Grow per Tick: 650
[13:56:10 INFO]: Clear tick list: false
[13:56:10 INFO]: Experience Merge Radius: 3.0
[13:56:10 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[13:56:10 INFO]: Max Entity Collisions: 8
[13:56:10 INFO]: Arrow Despawn Rate: 1200
[13:56:10 INFO]: Item Merge Radius: 2.5
[13:56:10 INFO]: Item Despawn Rate: 6000
[13:56:10 INFO]: Anti X-Ray: true
[13:56:10 INFO]:        Engine Mode: 1
[13:56:10 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[13:56:10 INFO]:        Replace Blocks: [1, 5]
[13:56:10 INFO]: Cactus Growth Modifier: 100%
[13:56:10 INFO]: Cane Growth Modifier: 100%
[13:56:10 INFO]: Melon Growth Modifier: 100%
[13:56:10 INFO]: Mushroom Growth Modifier: 100%
[13:56:10 INFO]: Pumpkin Growth Modifier: 100%
[13:56:10 INFO]: Sapling Growth Modifier: 100%
[13:56:10 INFO]: Wheat Growth Modifier: 100%
[13:56:10 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[13:56:10 INFO]: Mob Spawn Range: 4
[13:56:10 INFO]: Nerfing mobs spawned from spawners: false
[13:56:10 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[13:56:10 INFO]: Sending up to 5 chunks per packet
[13:56:10 INFO]: Max TNT Explosions: 100
[13:56:10 INFO]: Alternative Hopper Ticking: false
[13:56:10 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[13:56:10 INFO]: Structure Info Saving: true
[13:56:10 INFO]: Random Lighting Updates: false
[13:56:10 INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[13:56:10 INFO]: Zombie Aggressive Towards Villager: true
[13:56:10 INFO]: -------- World Settings For [world_the_end] --------
[13:56:10 INFO]: Keep spawn chunk loaded: true
[13:56:10 INFO]: WorldServer TickNextTickList cap set at 10000
[13:56:10 INFO]: WorldServer TickNextTickList cap always processes redstone: false
[13:56:10 INFO]: World async lighting: false
[13:56:10 INFO]: Remove invalid mob spawner tile entities: true
[13:56:10 INFO]: Player blocking damage multiplier set to 0.5
[13:56:10 INFO]: Max height for cactus growth 3. Max height for reed growth 3
[13:56:10 INFO]: Squids will spawn between Y: 45.0 and Y: 63.0
[13:56:10 INFO]: Living Entity Despawn Ranges:  Soft: 32 Hard: 128
[13:56:10 INFO]: Water over lava flow speed: 5
[13:56:10 INFO]: Inverted Redstone Lamps: false
[13:56:10 INFO]: Allow undead horse types to be leashed: true
[13:56:10 INFO]: Preparing start region for level 0 (Seed: 8420879462587617113)
[13:56:11 INFO]: Preparing start region for level 1 (Seed: 8420879462587617113)
[13:56:11 INFO]: Preparing start region for level 2 (Seed: 8420879462587617113)
[13:56:12 INFO]: [Atlas] Enabling Atlas v1.1.1
[13:56:12 INFO]: Loading Atlas...
[13:56:12 ERROR]: Error occurred while enabling Atlas v1.1.1 (Is it up to date?)
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 16 chars (attempted 18 - 'Atlas_Data_Request.
        at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:178) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at cc.funkemunky.api.Atlas.onEnable(Atlas.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
[13:56:12 INFO]: [Iris] Enabling Iris v1.6.4
[13:56:13 INFO]: Found executableCommand ConfigSetting (default=[kick %player% [IRIS] You have been kicked for failing %check%]).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:13 INFO]: Found key ConfigSetting (default=).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:13 INFO]: Found alertMessage ConfigSetting (default=[Iris] %player% has failed %check% (x%vl%)).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:13 INFO]: Found alertsDelay ConfigSetting (default=1000).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:13 INFO]: Found testMode ConfigSetting (default=false).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:13 INFO]: Found printToConsole ConfigSetting (default=false).
[13:56:13 INFO]: Value not found in configuration! Setting default into config...
[13:56:14 INFO]: Found enableOnJoin ConfigSetting (default=true).
[13:56:14 INFO]: Value not found in configuration! Setting default into config...
[13:56:14 WARN]: java.lang.NullPointerException
[13:56:14 WARN]:        at cc.funkemunky.anticheat.api.data.stats.StatsManager.<init>(StatsManager.java:25)
[13:56:14 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:56:14 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[13:56:14 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[13:56:14 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[13:56:14 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.lambda$initializeScanner$11(Iris.java:196)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[13:56:14 WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.Sink$ChainedReference.end(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.initializeScanner(Iris.java:191)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.startScanner(Iris.java:136)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.onEnable(Iris.java:67)
[13:56:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[13:56:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:56:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[13:56:14 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[13:56:14 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[13:56:14 WARN]: java.lang.NullPointerException
[13:56:14 WARN]:        at cc.funkemunky.anticheat.api.data.logging.LoggerManager.<init>(LoggerManager.java:25)
[13:56:14 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:56:14 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[13:56:14 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[13:56:14 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[13:56:14 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.lambda$initializeScanner$11(Iris.java:196)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[13:56:14 WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.SortedOps$RefSortingSink.end(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.Sink$ChainedReference.end(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:56:14 WARN]:        at java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.initializeScanner(Iris.java:191)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.startScanner(Iris.java:136)
[13:56:14 WARN]:        at cc.funkemunky.anticheat.Iris.onEnable(Iris.java:67)
[13:56:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[13:56:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[13:56:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412)
[13:56:14 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476)
[13:56:14 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494)
[13:56:14 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
[13:56:14 INFO]: Found UpdaterListener Bukkit listener. Registering...
[13:56:14 INFO]: Found notifyOnJoin ConfigSetting (default=true).
[13:56:14 INFO]: Value not found in configuration! Setting default into config...
[13:56:14 INFO]: Found checkForUpdates ConfigSetting (default=true).
[13:56:14 INFO]: Value not found in configuration! Setting default into config...
[13:56:14 INFO]: Found XdtW Atlas listener. Registering...
[13:56:14 INFO]: Found lHao Bukkit listener. Registering...
[13:56:14 INFO]: Found xgpd Bukkit listener. Registering...
[13:56:14 INFO]: Found ZdLc Atlas listener. Registering...
[13:56:14 INFO]: Found Pdmq Bukkit listener. Registering...
[13:56:14 INFO]: Connecting to Iris Anticheat servers...
[13:56:14 INFO]: Attempting to inject into netty
[13:56:14 INFO]: Server channel handler injected ([id: 0xa6ead2a6, /0:0:0:0:0:0:0:0:25565])
[13:56:14 INFO]: Your license key is valid. Enjoy Iris.
[13:56:14 ERROR]: Error occurred while enabling Iris v1.6.4 (Is it up to date?)
java.lang.NullPointerException
        at cc.funkemunky.anticheat.api.data.stats.StatsManager.<init>(StatsManager.java:25) ~[?:?]
        at cc.funkemunky.anticheat.Iris.onEnable(Iris.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:354) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:328) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:284) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:227) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
[13:56:14 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:56:14 INFO]: Done (4.823s)! For help, type "help" or "?"
[13:56:51 INFO]: UUID of player QuantumComputers is ef27883a-dd7e-400f-85c4-474b88933172
[13:57:13 WARN]:        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[13:57:13 WARN]:        at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[13:57:13 WARN]:        at cc.funkemunky.api.utils.blockbox.boxes.BlockBox1_7_R4.getCollidingBoxes(BlockBox1_7_R4.java:69)
[13:57:13 WARN]:        at cc.funkemunky.anticheat.api.data.processors.MovementProcessor.update(MovementProcessor.java:46)
[13:57:13 WARN]:        at ZdLc.onEvent(PacketListeners.java:122)
[13:57:13 WARN]:        ... 11 more

**Comment by FozzieHi** [comment]
Please try this with the latest version of [Iris](https://www.spigotmc.org/resources/iris-anticheat-advanced-cheat-detection-1-7-1-13.53721/)
