### ISSUE TITLE
KillAura Java Error

### ISSUE THREAD

**Issue by JasperWorld** [funkemunky/Iris-Issues#7]
**Describe the bug**

**Version Information**
- Iris Anticheat Version: 1.5.2.1
- Atlas Version: 1.0.6
- Bukkit/Spigot Version: 1.8.8

**Server Logs**
[16:07:37 WARN]: java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
[16:07:37 WARN]:        at java.util.concurrent.FutureTask.report(Unknown Source)
[16:07:37 WARN]:        at java.util.concurrent.FutureTask.get(Unknown Source)
[16:07:37 WARN]:        at NXyn.hopper(PacketListeners.java:194)
[16:07:37 WARN]:        at NXyn.onEvent(PacketListeners.java:161)
[16:07:37 WARN]:        at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
[16:07:37 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:07:37 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:07:37 WARN]:        at cc.funkemunky.api.event.system.EventManager.call(EventManager.java:66)
[16:07:37 WARN]:        at cc.funkemunky.api.event.system.EventManager.lambda$callEvent$1(EventManager.java:49)
[16:07:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:07:37 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[16:07:37 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[16:07:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[16:07:37 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[16:07:37 WARN]:        at java.lang.Thread.run(Unknown Source)
[16:07:37 WARN]: Caused by: java.util.ConcurrentModificationException
[16:07:37 WARN]:        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[16:07:37 WARN]:        at java.util.ArrayList$Itr.next(Unknown Source)
[16:07:37 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getEntities(CraftWorld.java:626)
[16:07:37 WARN]:        at cc.funkemunky.api.tinyprotocol.packet.in.WrappedInUseEntityPacket.process(WrappedInUseEntityPacket.java:32)
[16:07:37 WARN]:        at cc.funkemunky.api.tinyprotocol.api.NMSObject.<init>(NMSObject.java:42)
[16:07:37 WARN]:        at cc.funkemunky.api.tinyprotocol.packet.in.WrappedInUseEntityPacket.<init>(WrappedInUseEntityPacket.java:25)
[16:07:37 WARN]:        at XSYH.onPacket(KillauraA.java:33)
[16:07:37 WARN]:        at NXyn.lambda$hopper$0(PacketListeners.java:176)
[16:07:37 WARN]:        ... 6 more

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) Activated KillAura in my Wurst Client
2) The first time Iris tried to flag me I got the error above.

**Comment by funkemunky** [comment]
Thanks for the report, this has been fixed for the next update.
