### ISSUE TITLE
Bug Report Iris

### ISSUE THREAD

**Issue by Peebbong** [funkemunky/Iris-Issues#97]
**Describe the bug**

**Version Information**
- Iris Anticheat Version Latest
- Atlas Version Latest
- Bukkit/Spigot Version 1.8.8

**Are you using the ViaVersion plugin?**
Yes

**Server Logs**
[15:24:50 ERROR]: Could not pass event PlayerMoveEvent to Iris v1.8.3
 org.bukkit.event.EventException
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
 at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
 at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
 at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
 Caused by: java.lang.NullPointerException
 at NxDu.onEvent(BukkitListeners.java:45) ~[?:?]
 at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
 ... 15 more

**Comment by FozzieHi** [comment]
Put the error log in a pastebin, I cannot read that at all.
